---
abstract: 'L<AnyEvent> based L<https://github.com/github/hubot>'
author:
  - 'Hyungsuk Hong <hshong@perl.kr>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300034, CPAN::Meta::Converter version 2.130880'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Hubot
requires:
  AnyEvent: 0
  AnyEvent::Campfire::Client: 0
  AnyEvent::HTTP: 0
  AnyEvent::HTTP::ScopedClient: 0
  AnyEvent::IRC::Client: 0
  Cwd: 0
  Encode: 0
  File::Slurp: 0
  Getopt::Long::Descriptive: 0
  HTTP::Request: 0
  JSON::XS: 0
  LWP::Protocol::https: 0
  LWP::UserAgent: 0
  Moose: 0
  Pod::Usage: 0
  Time::HiRes: 0
  Try::Tiny: 0
  URI: 0
  URI::QueryParam: 0
  namespace::autoclean: 0
  strict: 0
  warnings: 0
version: 0.1.10
