---
abstract: 'L<AnyEvent> based L<https://github.com/github/hubot>'
author:
  - 'Hyungsuk Hong <hshong@perl.kr>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
  File::ShareDir::Install: 0.03
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.006, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Hubot
requires:
  AnyEvent: 0
  AnyEvent::Campfire::Client: 0
  AnyEvent::HTTP: 0
  AnyEvent::HTTP::ScopedClient: 0
  AnyEvent::HTTPD: 0
  AnyEvent::IRC::Client: 0
  Cwd: 0
  Encode: 0
  File::Copy: 0
  File::Copy::Recursive: 0
  File::Path: 0
  File::ShareDir: 0
  File::Spec::Functions: 0
  HTTP::Request: 0
  JSON: 0
  JSON::XS: 0
  LWP::UserAgent: 0
  Moose: 0
  Pod::Usage: 0
  Time::HiRes: 0
  Try::Tiny: 0
  URI: 0
  URI::Escape: 0
  URI::QueryParam: 0
  namespace::autoclean: 0
version: 0.2.5
